- igneous/tasks.py
Using a `low_padding` value greather than 0 for a `MeshTask` introduces an additional voxel offset that we need to compensate for when calculating the final vertex positions.
> fix(MeshTask): _update_vertices() accounts for low_padding offset

- igneous/tasks/skeletonization/skeletonization.py
skipped to root node when path gets within soma_distance. Also prevented invalidation ball from running on root node.
> changed behavior of code around somas

- igneous/tasks.py
`cache_control` because I want to see meshes asap in Neuroglancer,
`parallel` because it looks Segmentation Download is the slowest part for quick&dirty meshing without simplification.
> feat(MeshTask): cache_control and parallel kwargs support

- .dockerignore
- Dockerfile
- requirements.txt
Reducing docker image size by
* only adding files to the Docker image that are actually required (no caches and eggs)
* removing build dependencies that are never used, or already installed
* removing requirements that are never imported in igneous itself
* collapsing the RUN layers to a single one (otherwise the cleanup is useless)
* removing libboost-dev after building the meshing library
* prevent pip from caching installation files
* removing some additional temporary/cached files from the installed site-packages
We could probably save quite some additional space if we switch to `python-slim` or even alpine... not sure how heavily others rely on the current images additional tools
Resolves #36
> refactor(Dockerfile): Reduce Docker image size

- igneous/task_creation.py
- igneous/tasks/skeletonization/tasks.py
- igneous/tasks/tasks.py
- test/test_tasks.py
This enables the following motif:
```python
import gevent.monkey
gevent.monkey.patch_all(thread=False)
import numpy as np
from cloudvolume import *
from taskqueue import GreenTaskQueue, MockTaskQueue, LocalTaskQueue
import igneous.task_creation as tc
def downsample():
cloudpath = '...'
return tc.create_downsampling_tasks(
cloudpath, 
mip=0, 
num_mips=5, 
fill_missing=True,
)
tasks = downsample()
tq = GreenTaskQueue('igneous-queue')
tq.insert_all(tasks, parallel=8)
```
> feat: support for parallel upload for grid-regular tasks

- igneous/tasks/tasks.py
Previous behavior:
Read src image at chunk aligned bounding box and write to offset bounding box--> non-aligned writes
New behavior:
Read src image at offset bounding box (inverted offset) and write to original chunk aligned bounding box
> refactor(TransferTask): translation without unaligned writes

- igneous/secrets.py
- igneous/task_execution.py
I needed this for local testing using a dockerized sqs queue, where the endpoint_url to boto3.client is required and credentials are not necessary.
https://hub.docker.com/r/roribio16/alpine-sqs/
> Allow boto3 client parameters region_name and endpoint_url

- igneous/tasks/mesh_graphene_remap.py
Porting this fix over from the ChunkedGraph (see here: https://github.com/seung-lab/PyChunkedGraph/pull/301), as the igneous graphene mesh generation code was based on the ChunkedGraph mesh generation code, where this bug originated.
> Fix: graphene mesh stealing bug

- ChangeLog
- README.md
- igneous/downsample_scales.py
- igneous/shards.py
- igneous/task_creation/image.py
- igneous/tasks/__init__.py
- igneous/tasks/image.py
- igneous_cli/cli.py
- test/test_shards.py
This feature adds sharded downsampling to Igneous. A highlight is that all sharding calculations are done completely automatically and it is as simple to use as:
```bash
igneous downsample $PATH --queue $QUEUE --sharded --mip 0
```
The default parameters pick shard constructions that easily fit into the memory of commodity hardware, making it simple to deploy.
A downside is that this constraint means only a single downsample level can be computed per run. In the future, it may be desirable to add additional downsample levels, but it will radically increase the amount of memory required. For the following reason:
```
Needed in memory:
1 mip: 1 shard
2 mips: 5 shards
3 mips: 21 shards
```
Perhaps it is possible to construct each shard in a more online fashion, but it seems tricky.
Another …
> feat: shard downsampling

- igneous/task_creation/image.py
This fixes `get_bounds` calls that rely on positional arguments that I broke in PR #108.
> fix: Add kwarg for updated get_bounds

- README.md
- igneous/task_creation/common.py
- igneous/task_creation/mesh.py
- igneous/task_creation/skeleton.py
- igneous/tasks/__init__.py
- igneous/tasks/mesh/mesh.py
- igneous/tasks/mesh/multires.py
- igneous/tasks/skeleton.py
- igneous_cli/cli.py
- requirements.txt
- test/test_shards.py
Adds several new features:
- `igneous view $DATASET` to open an on-disk dataset in neuroglancer
- `igneous mesh ... --sharded` generates fragments
- `igneous mesh merge-sharded ....`
- Changes sharded skeletons to automatically compute sharding config
- Create spatial index database from meshes `igneous mesh spatial-index create $PATH` `igneous mesh spatial-index db $PATH $DATABASE`
> feat: sharded meshes (single res using trivial multi-res)

- igneous/task_creation/mesh.py
- igneous/tasks/__init__.py
- igneous/tasks/mesh/mesh.py
- requirements.txt
- test/test_tasks.py
Use an os.scandir task on filesystems as prefix scans are redundant on FS.
> perf: streamlined manifest generation on filesystem

- igneous_cli/cli.py
We offer wayyy more formats than just cseg and compresso (jpeg, raw, png, fpzip, kempressed, just to name a few). The user should be able to pick whatever they want.
> redesign(cli): change --cseg and --compresso flags to --encoding

- igneous/tasks/skeleton.py
* line 238: here is nothing named 'skel', and maybe 'skeleton';
* line 258: this 'progress=True' would generate double 'tqdm';
* line 264: this skel has no key named 'filename', but has 'path', maybe a problem with the name version.
I ran into these issues while testing ‘unsharded skeleton’, and by the way, the ‘sharded' version is charming!
> Some inappropriate code at UnshardedSkeletonMergeTask

- igneous/task_creation/image.py
`create_transfer_tasks` currently doesn't pass its `factor` kwarg to `create_downsample_scales` which assumes `factor=(2, 2, 1)`. If the user wants a different downsampling factor this results in inconsistent downsampled layers.
> fix: use factor arg within create_transfer_tasks

- igneous/task_creation/common.py
- igneous/task_creation/image.py
- igneous/tasks/image/image.py
- igneous_cli/cli.py
Adds `--encoding-level` to `igneous image xfer` which allows you to control jpeg quality, png level, and fpzip precision. This gets added to the info file as `jpeg_quality`, `png_level`, and `fpzip_precision` on the indicated scale. All other scales will continue to use defaults unless the correct parameter is present.
> feat: add encoding level to transfer tasks

- igneous/task_creation/image.py
I think this is what was intended, but let me know if I read the code incorrectly.
> fix unbound local error in image xfer --cutout

- igneous/task_creation/mesh.py
- igneous/task_creation/skeleton.py
- igneous/tasks/mesh/mesh.py
- igneous/tasks/mesh/multires.py
- igneous/tasks/skeleton.py
This PR makes two changes to reduce read api calls when created sharded formats:
1. Cache spatial_index files. Because all the spatial_index are used by each skeleton/mesh merge tasks, the total reads goes quadratically with the volume (total number of spatial_index files x total number of tasks). Cache it makes the growth linear.
2. Optionally save the intermediary *.frag files to a separate location specified by frag_path. To create sharded format, each segment must be read from frag files at least once. Save and read them from a shared nfs volume reduces the read requests significantly.
> Reduce read requests when creating sharded skeletons and meshes

- igneous_cli/cli.py
Adds support for `--xrange`, `--yrange`, and `--zrange` optional parameters to the `image rm` command in the CLI.
> feat: support --xrange,--yrange,--zrange in `image rm` 

- README.md
- igneous/task_creation/skeleton.py
- igneous/tasks/skeleton.py
- igneous_cli/cli.py
- requirements.txt
- test/test_tasks.py
Adds `cross_sectional_area=True` and `cross_sectional_area_smoothing_window=1` to `SkeletonTask`.
As of this writing, the xs3d module kimimaro uses is too slow to do a dense calculation (think: 8+ hrs per a task) but is fast enough to do it for sparse neurons (thousands of times less work).
> feat(SkeletonTask): compute cross sectional area

- README.md
- igneous/task_creation/mesh.py
- igneous/task_creation/skeleton.py
Currently, running the example code with default arguments `mesh_dir=None`
- `create_meshing_tasks` leads to the creation of `LAYER/mesh_mip_0_err_40` (ignoring the value of `vol.info['mesh']`)
- `create_mesh_manifest_tasks` on the other hand tries to read/write from `LAYER/{vol.info["mesh"]}` https://github.com/seung-lab/igneous/blob/5f9f18f7f84e547cbf6f15c9bcd5b959581d0bed/igneous/task_creation/mesh.py#L63 https://github.com/seung-lab/igneous/blob/5f9f18f7f84e547cbf6f15c9bcd5b959581d0bed/igneous/tasks/mesh/mesh.py#L576
This and some minor `README.md` improvements.
> make mesh_dir behavior consistent across create_meshing_tasks and create_mesh_manifest_tasks

- igneous/tasks/mesh/multires.py
Hello!
We (myself and @aranega) were using igneous to convert some meshes to neuroglancer precomputed format, and we noticed some cracks could appear in neuroglancer in the mesh when switching between resolutions for the mesh in neuroglancer.
If you load just one LOD in neuroglancer the mesh was fine, but when neuroglancer tried to load a low res mesh first and then start filling in certain parts of the octree with a higher res mesh there could be cracks that appear in neuroglancer.
When we looked into it, it appeared to be because the triangles from the low res mesh could cross the bounds in the octree at the lower levels of the tree, which meant neuroglancer couldn't correctly remove all the triangles from the low res mesh when loading a higher res mesh. Here's a comparison with/without …
> Help with cracks in large meshes when switching between resolutions in neuroglancer

- igneous/__init__.py
- igneous/downsample_scales.py
- igneous/task_creation/image.py
- igneous/tasks/image/image.py
- igneous_cli/cli.py
- test/layer_harness.py
- test/test_ccl_tasks.py
- test/test_tasks.py
- test/test_transfer_tasks.py
Multi-mip sharded downsampling. Previously, only a single mip could be generated at a time.
The previous algorithm read 1-2 z chunks at a time, downsampled, and built a single shard. This allowed for reasonable memory consumption.
This new algorithm reads 1-2 chunks at a time, downsamples them, and stores them compressed in a dictionary. With more mip levels, the amount of image data grows tremendously, but for lossy compressed images or segmentation, compression will give a sufficient compression factor for this to be reasonable. E.g. segmentation can compress hundreds of times, lossy images can compress maybe 4-5x.
For losslessly compressed images, expect very large memory usage if using num_mips > 2. E.g. 16 + 4 + 1 = 21 shards * 0.7 = 14.7x.
> feat: multi-mip sharded downsampling

- igneous/tasks/skeleton.py
- requirements.txt
- test/test_tasks.py
Uses CloudVolume renumbered downloads to reduce the size of the u64 labels and more carefully manages its lifecycle.
This was necessary because the addition of aggressive hole filling and cross section analysis were increasing the memory requirements such that out of memory errors were occurring during cluster processing.
This run seems to give fairly impressive results (blue) old code (black) new code
This run is more ambiguous. (blue) old code (black) new code (red) new code. 
At least the initial download shows a benefit in memory consumption.
> perf: lower memory skeletonization

- igneous/tasks/mesh/multires.py
- requirements.txt
Uses new `zmesh.chunk_mesh` in zmesh==1.9.0 to accelerate mesh chunking
> perf(multires meshes): vastly faster mesh chunking
